#!/usr/bin/env node
/**
 * gen-catalog.mjs — generate the skills + integrations catalogs for a workspace.
 *
 * Reads:
 *   <repo>/.claude/skills/<name>/SKILL.md   (frontmatter: name, description, kind, triggers)
 *   <repo>/.claude/integrations.json        (curated integrations manifest)
 * Writes:
 *   <repo>/.claude/skills/INDEX.md          (skills catalog — agent + human readable)
 *   <repo>/.claude/INTEGRATIONS.md          (integrations catalog)
 *
 * Zero-dep. Run after adding/removing a skill or editing integrations.json.
 *   node scripts/gen-catalog.mjs [--repo <path>]   (default: cwd)
 */

import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// ── tiny YAML-frontmatter reader (handles inline, `|` and `>` block scalars, simple lists) ──
export function frontmatter(md) {
  const m = md.match(/^---\n([\s\S]*?)\n---/);
  if (!m) return {};
  const lines = m[1].split("\n");
  const out = {};
  let key = null, block = null, blockMode = null, list = null;
  const flush = () => {
    if (key && block !== null) {
      out[key] = blockMode === ">" ? block.join(" ").replace(/\s+/g, " ").trim() : block.join("\n").trim();
      block = null; blockMode = null;
    }
    if (key && list !== null) { out[key] = list; list = null; }
    key = null;
  };
  for (const raw of lines) {
    const top = raw.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    const isIndented = /^\s+/.test(raw);
    if (top && !isIndented) {
      flush();
      key = top[1];
      const val = top[2];
      if (val === "|" || val === ">") { blockMode = val; block = []; }
      else if (val === "") { list = []; } // may become a list (- items) or stay empty
      else { out[key] = val.replace(/^["']|["']$/g, ""); key = null; }
    } else if (key && block !== null) {
      block.push(raw.replace(/^\s{2}/, ""));
    } else if (key && list !== null) {
      const li = raw.match(/^\s*-\s*(.*)$/);
      if (li) list.push(li[1].replace(/^["']|["']$/g, "").trim());
    }
  }
  flush();
  return out;
}

export function firstSentence(s = "") {
  const clean = s.replace(/\s+/g, " ").trim();
  const dot = clean.indexOf(". ");
  return dot === -1 ? clean : clean.slice(0, dot + 1);
}

// Parse a workspace's skills into [{name, kind, description, triggers, workflow}].
export function readSkills(repoDir) {
  const dir = path.join(repoDir, ".claude", "skills");
  const out = [];
  if (!existsSync(dir)) return out;
  for (const name of readdirSync(dir).sort()) {
    const sub = path.join(dir, name);
    const skillMd = path.join(sub, "SKILL.md");
    if (!statSync(sub).isDirectory() || !existsSync(skillMd)) continue;
    const fm = frontmatter(readFileSync(skillMd, "utf8"));
    out.push({
      name: fm.name || name,
      kind: fm.kind || "skill",
      description: fm.description || "",
      triggers: Array.isArray(fm.triggers) ? fm.triggers : [],
      workflow: fm.workflow || null,
    });
  }
  return out;
}

// Parse a workspace's integrations manifest into an array (empty on missing/invalid).
export function readIntegrations(repoDir) {
  const p = path.join(repoDir, ".claude", "integrations.json");
  if (!existsSync(p)) return [];
  try { return JSON.parse(readFileSync(p, "utf8")).integrations || []; }
  catch { return []; }
}

function generate(repo) {
const skillsDir = path.join(repo, ".claude", "skills");
const skills = readSkills(repo);
const integrations = readIntegrations(repo);

// ── render skills INDEX.md ──
const harnesses = skills.filter((s) => s.kind === "workflow-harness");
const others = skills.filter((s) => s.kind !== "workflow-harness");
let sk = `# Skills Catalog\n\n` +
  `> Generated by \`scripts/gen-catalog.mjs\` — do not edit by hand. ` +
  `Re-run after adding or changing a skill.\n\n` +
  `This workspace ships **${skills.length}** skill(s). Skills activate automatically when ` +
  `their description matches what you ask; you can also invoke one by name.\n\n`;

if (harnesses.length) {
  sk += `## Dynamic-workflow harnesses\n\nMulti-agent harnesses with adversarial verification / rubric-gated self-correction.\n\n`;
  sk += `| Skill | What it does | Run when |\n|---|---|---|\n`;
  for (const s of harnesses) {
    const trig = s.triggers.length ? s.triggers.slice(0, 3).join("; ") : "—";
    sk += `| \`${s.name}\` | ${firstSentence(s.description)} | ${trig} |\n`;
  }
  sk += `\n`;
}
if (others.length) {
  sk += `## Skills\n\n| Skill | What it does |\n|---|---|\n`;
  for (const s of others) sk += `| \`${s.name}\` | ${firstSentence(s.description)} |\n`;
  sk += `\n`;
}
sk += `## Share a skill\n\nPush a skill to the Team Brain so teammates can pull it:\n\n` +
  "```bash\naios push skill <name>      # share SKILL.md + its reference files\naios pull skill <name>      # fetch a shared skill into 1-inbox/from-brain/skills/\naios install-skill <name>   # promote a pulled skill into .claude/skills/ (explicit, append-only)\n```\n\n" +
  `Pulled skills are executable code — install is always a deliberate act; they never auto-activate on pull.\n`;
writeFileSync(path.join(skillsDir, "INDEX.md"), sk);

// ── render INTEGRATIONS.md ──
const byCat = {};
for (const i of integrations) (byCat[i.category] ||= []).push(i);
const wired = integrations.filter((i) => i.status === "wired").length;
let ig = `# Integrations Catalog\n\n` +
  `> Generated by \`scripts/gen-catalog.mjs\` from \`.claude/integrations.json\` — do not edit by hand.\n\n` +
  `**${integrations.length}** connectable tools · **${wired}** wired. ` +
  `To connect one: copy its server from \`.mcp.example.json\` into \`.mcp.json\`, set the env vars, ` +
  `then flip its \`status\` to \`wired\` in \`.claude/integrations.json\` and re-run \`gen:catalog\`. ` +
  `Full setup notes: [\`docs/integrations.md\`](../../docs/integrations.md).\n\n`;
for (const cat of Object.keys(byCat).sort()) {
  ig += `## ${cat.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())}\n\n`;
  ig += `| Tool | Status | How | What you get |\n|---|---|---|---|\n`;
  for (const i of byCat[cat]) {
    const badge = i.status === "wired" ? "✅ wired" : "○ available";
    ig += `| **${i.name}** | ${badge} | ${i.transport.toUpperCase()} | ${i.summary} |\n`;
  }
  ig += `\n`;
}
writeFileSync(path.join(repo, ".claude", "INTEGRATIONS.md"), ig);

console.log(`catalog: ${skills.length} skill(s) → .claude/skills/INDEX.md · ${integrations.length} integration(s) → .claude/INTEGRATIONS.md`);
}

// ── CLI entry (only when run directly, not when imported) ──
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const argv = process.argv.slice(2);
  const repo = path.resolve(argv.includes("--repo") ? argv[argv.indexOf("--repo") + 1] : process.cwd());
  generate(repo);
}
